export enum ToolCategory {
  LLM = 'LLM',
  VIDEO_GENERATION = 'VIDEO_GENERATION',
  IMAGE_GENERATION = 'IMAGE_GENERATION',
  AUDIO = 'AUDIO',
  SEARCH = 'SEARCH',
  BROWSER_AUTOMATION = 'BROWSER_AUTOMATION',
  STORAGE = 'STORAGE',
  DATABASE = 'DATABASE',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  EMAIL = 'EMAIL',
  CALENDAR = 'CALENDAR',
  WEBHOOKS = 'WEBHOOKS',
}
